### ISSUE TITLE
How to remove the dot from "Spotify."?

### ISSUE THREAD

**Issue by adamaharony** [nations/spoticord#19]
Please send help my OCD can't stand that anymore!
![image](https://user-images.githubusercontent.com/26117672/33487819-3a96ad28-d6b7-11e7-9bd5-97b13d75696e.png)

**Comment by cernodile** [comment]
You can't, unfortunately "Spotify" is reserved by Discord for their plan of Spotify interigation.

**Comment by adamaharony** [comment]
@cernodile Alrighty then. Do you know of a way to change all of the "Spotify." message? I think I have a snazzy workaround.

**Comment by foxt** [comment]
@CringyAdam You'd have to create your own app at https://discordapp.com/developers/applications/me/create with all the assets and setup.

**Comment by adamaharony** [comment]
@theLMGN and @cernodile: Thank you for your help. I really appreciate it.

**Comment by Phineas** [comment]
What should I change it to if not “Spotify.”? Maybe “Music”, “Spotify Music” or something?

**Comment by cernodile** [comment]
@Phineas "Spotify Music" seems reasonable. "Music" would be too generic, as if you were listening to from anything else.

**Comment by Phineas** [comment]
Done.

**Comment by itslukej** [comment]
Would it be possible to add a ZWS? Like `Spotify​` (theres a ZWS at the end)
