### ISSUE TITLE
Detect when the spotify web helper is closed and stop searching for the socket.

### ISSUE THREAD

**Issue by dustinrouillard** [nations/spoticord#24]
This error is just a bit annoying to look at and I think you should do something so that when the error arises it either checks less often for the helper or just stops checking altogether, if you can make it stop and then start again when it detects the web helper then that would be even better.

Hopefully something can be done on this. 

The error that I'm talking about that is kinda annoying, if you cannot do anything about fixing this maybe just make it a one line error that says something like

`[01:09:19] Failed to fetch Spotify data: Cannot connect to web helper`
or something similar instead of what's below.

```
[01:09:19] Failed to fetch Spotify data: { Error: connect ECONNREFUSED 127.0.0.1:4381
    at Object._errnoException (util.js:1026:11)
    at _exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 4381 }
```

**Comment by cernodile** [comment]
Does my PR #25 satisfy what you want? Killing process would put `pm2` processes on a restart loop, so that's crossed out of the list.

**Comment by Phineas** [comment]
Fixed. #25
