### ISSUE TITLE
Offering the app as an executable file

### ISSUE THREAD

**Issue by kettui** [nations/spoticord#28]
I came across [pkg](https://github.com/zeit/pkg) some months ago but never found a use case for it with my own projects. This project however seems like a good fit for it, so I figured I'd drop it in as a suggestion.

Basically spoticord could be packaged to a single executable file to eliminate all the hassle that comes with setting up node, installing dependencies, running the app and so forth. For many of us this process obviously isn't that big of an issue, but I'm sure there are a lot of people who'd rather just skip the hassle and use a pre-built executable instead.

I personally tried it out and the packaging is literally as simple as installing pkg and running the command `pkg -t node8-win app.js` (built it for windows in my case), and it works as one would expect.

**Comment by cernodile** [comment]
Wouldn't this make plethora of issues involving antiviruses and SmartScreen due to being an unsigned application?
