### ISSUE TITLE
"no git binary found in $Path"

### ISSUE THREAD

**Issue by GloriousAlpaca** [nations/spoticord#30]
I cannot install the Program because of this error:
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Andreas\AppData\Roaming\npm-cache\_logs\2017-12-03T09_08_03_852Z-debug.log
[2017-12-03T09_08_03_852Z-debug.log](https://github.com/nations/spoticord/files/1524605/2017-12-03T09_08_03_852Z-debug.log)

**Comment by cernodile** [comment]
You don't have git. Please install git.

**Comment by GloriousAlpaca** [comment]
Ah, Thanks!
