### ISSUE TITLE
Ads cause spoticord to error out

### ISSUE THREAD

**Issue by Travis-T** [nations/spoticord#4]
`spoticord\app.js:24
    if(res.track.track_resource.uri == currentSong.uri) return;
                                ^
TypeError: Cannot read property 'uri' of undefined
`
Ads do not have a uri, so when spotify plays an ad the program errors out, just check if the current track is an ad before checking if it is the same song.

**Comment by Phineas** [comment]
This should be fixed in 22144082858ac5067f27f19b683c0cc977739036 - Thanks!
