### ISSUE TITLE
freezes when doing `npm i`

### ISSUE THREAD

**Issue by ghost** [nations/spoticord#40]
I'm on Ubuntu 17.10 using bash when I do `npm i` it says `loadDep:register-scheme` and never changes, ask me if you want any other information.

**Comment by Phineas** [comment]
This isn't an issue with spoticord, submit an issue here:
https://github.com/npm/npm/issues/new

**Comment by cernodile** [comment]
Works for me on Ubuntu 17.10, try running npm with sudo
