### ISSUE TITLE
Stuck at "Connected to Discord!"

### ISSUE THREAD

**Issue by vincentlarkin** [nations/spoticord#42]
I did everything, had Spotify and discord running before hand, I ran node app.js and it just has the "Connected to Discord!" message. It does not show up as status bar message or anything. Help would be appreciated. Thanks

**Comment by cernodile** [comment]
Check your hosts file, remove anything related to Spotify, else try closing Spotify for a minute and reopening

**Comment by vincentlarkin** [comment]
Removing Spotify Ad Blocks from my hosts file worked. Thanks.
