### ISSUE TITLE
You must install peer dependencies yourself.

### ISSUE THREAD

**Issue by alv314** [nations/spoticord#43]
I apologize if this is a relatively easy issue to solve but I'm not very familiar with this. I run `npm i`
and this is what comes up.

>  register-protocol-handler.vcxproj -> C:\Users\alico\spoticord\node_modules\reg                                                                               ister-scheme\build\Release\\register-protocol-handler.node
  register-protocol-handler.vcxproj -> C:\Users\alico\spoticord\node_modules\reg                                                                               ister-scheme\build\Release\register-protocol-handler.pdb (Full PDB)
npm WARN discord.js@12.0.0-dev requires a peer of bufferutil@^3.0.0 but none is                                                                                installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of erlpack@discordapp/erlpack but                                                                                none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of node-opus@^0.2.0 but none is i                                                                               nstalled. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of opusscript@^0.0.4 but none is                                                                                installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of sodium@^2.0.0 but none is inst                                                                               alled. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of libsodium-wrappers@^0.7.0 but                                                                                none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of uws@^8.14.0 but none is instal                                                                               led. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of zlib-sync@^0.1.0 but none is i                                                                               nstalled. You must install peer dependencies yourself.
npm WARN eslint-config-google@0.9.1 requires a peer of eslint@>=4.1.1 but none i                                                                               s installed. You must install peer dependencies yourself.

**Comment by Phineas** [comment]
It's just a warning, don't worry. Thanks though!
