### ISSUE TITLE
Not really an issue, but can you replace the text showing "Spotify Music" in discord to sth else?

### ISSUE THREAD

**Issue by D1yt** [nations/spoticord#51]
Searched through the files for "Spotify Music" which is shown as the current game in discord but I could not find it.

**Comment by cominixo** [comment]
The name "Spotify Music" is actually in the discord application that he made so you need to make a new app (https://discordapp.com/developers/applications/me/create), make the name of the app the text you want to see, enable rich presence in it and then change the "appClientID" in the keys.json file to the id of the app that you made. The app that you made also needs to have the assets "spotify", "play_button_clean" and "pause_button_clean" to match with the keys.json file.

**Comment by D1yt** [comment]
Thanks for your answer. But I'm kinda struggling with creating the app. What REDIRECT URL should I use? What is the APP ICON doing? And most importantly, how exactly do I add the ASSETS? I need to add pictures and give them a type. So what do I add as pictures?

**Comment by D1yt** [comment]
okay, actually the most important thing right now, is to get it to work but my Token is unexpected (changed it in the keys.json
`SyntaxError: E:\Desktop\SPOTICORD\keys.json: Unexpected token a in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:643:27)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\Desktop\SPOTICORD\app.js:6:14)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)`

**Comment by D1yt** [comment]
nevermind, i'm an idiot, thanks for your help ^^

**Comment by cominixo** [comment]
Did you get everything working? I don't think the app icon and the redirect url matter, the assets should look like this: 
![chrome_2017-12-18_11-56-21](https://user-images.githubusercontent.com/22600756/34109404-998f0f10-e3ea-11e7-9e9c-ffdeec844d64.png)
The image in the assets can be anything you want.

**Comment by D1yt** [comment]
yeah, everything working fine now, thanks again

**Comment by cominixo** [comment]
You're welcome, have a nice day!
