### ISSUE TITLE
 README.md Missing Instructions

### ISSUE THREAD

**Issue by realdevon** [nations/spoticord#61]
When I installed the package I also had to install wintools, request, and discord-rpc, which weren't in the instructions. This was fine for me because I knew what the errors meant but for users unfamiliar with JS this could be very confusing.

**Comment by JasonKhew96** [comment]
[Install the modules `npm i` or `yarn`](https://github.com/nations/spoticord#setup)
run this command in `spoticord` directory.

**Comment by cernodile** [comment]
`package.json` contains enough information to install wintools, request, discord-rpc with the given instruction of `npm i`.
