### ISSUE TITLE
RPC_Connection_Timeout

### ISSUE THREAD

**Issue by danyy666** [nations/spoticord#63]
Trying to use Spoticord with Canary, but I get in this error:

 { Error [RPC_CONNECTION_TIMEOUT]
    at Timeout.setTimeout [as _onTimeout] (C:\Users\Danyy\Desktop\spoticord-master\node_modules\discord-rpc\src\Client.js:107:47)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5) [Symbol(code)]: 'RPC_CONNECTION_TIMEOUT' }

any way to fix this? Both Spoticord and Canary are updated to last version.

**Comment by danyy666** [comment]
Edit: Works fine on Discord, but still getting that error on Canary.

**Comment by JasonKhew96** [comment]
Canary works fine (Windows 10 64bit)
``` spoticord: '0.0.4',
  npm: '5.6.0',
  ares: '1.13.0',
  cldr: '32.0',
  http_parser: '2.7.0',
  icu: '60.1',
  modules: '59',
  nghttp2: '1.25.0',
  node: '9.2.1',
  openssl: '1.0.2n',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.16.1',
  v8: '6.2.414.44-node.11',
  zlib: '1.2.11' 
```

**Comment by cernodile** [comment]
This is a discord-rpc module issue, not Spoticord's, please check their [repository here.](https://github.com/devsnek/discord-rpc)
