### ISSUE TITLE
When I play a song, I get this error.

### ISSUE THREAD

**Issue by LilBirdyCodes** [nations/spoticord#69]
[15:05:39] Connected to Discord! (385061381344591872)
[15:05:43] Updated song to: mxmtoon - feelings are fatal
(node:63416) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: (Date.now(...) - EPOCH).toString(...).padStart is not a function
(node:63416) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Any fixes?

**Comment by Phineas** [comment]
Please make sure you're using the most recent version of NodeJS
