### ISSUE TITLE
All of a sudden there are a bunch of dependencies I need to download but I don't know what they are

### ISSUE THREAD

**Issue by bigmoutard** [nations/spoticord#72]
I've used Spoticord without a problem a month or two ago. I stopped for a bit and now I'm trying to use it again but uhhhh I get this 
![image](https://user-images.githubusercontent.com/36018206/35654559-af5f04a0-06bb-11e8-8122-50724365ccdd.png)

I don't know what this means bc I'm a java noob.

**Comment by bigmoutard** [comment]
Oh wow, okay, NOW it works. Dunno what I've been doing wrong for the past 20 minutes but it's all good now. 
![image](https://user-images.githubusercontent.com/36018206/35654710-3b5717a4-06bc-11e8-8621-21f6a4be15f3.png)

**Comment by JackKellyBayliss** [comment]
Those messages you’re receiving are only warning messages. I receive these messages but Spoticord still works perfectly.

**Comment by bigmoutard** [comment]
Yeah it wasn't working at all until now. idk why this time was different even though I had done the node app.js thing before as well /shrug
