### ISSUE TITLE
Time Elapsed changed in Canary to [value] left

### ISSUE THREAD

**Issue by Mei-Cree** [nations/spoticord#8]
[https://i.imgur.com/MyMNzPn.png](url)

**Comment by Phineas** [comment]
Did you modify the code at all? This shouldn’t happen

**Comment by Mei-Cree** [comment]
I restarted my comp, and that's about it, Discord Canary did update though.

**Comment by Pierce01** [comment]
newest canary update removes it

**Comment by Phineas** [comment]
^ this is correct, I hope they add it back soon ):

**Comment by Mei-Cree** [comment]
It is back now

**Comment by dustinrouillard** [comment]
This was put back, my guess is they didn't mean to remove it.
https://government-database.info/UQSXFdn.png
